# Generated by Django 6.0 on 2025-12-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('COMMISSION', 'Commission'), ('BET_WIN', 'Bet Win'), ('BET_LOSS', 'Bet Loss'), ('REGISTRATION_FEE', 'Registration Fee')], max_length=20),
        ),
    ]
